apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdl-fullmakt
  namespace: default
  labels:
    team: pdl-fullmakt
spec:
  image: docker.pkg.github.com/nais/testapp/testapp:latest
  port: 8080
  liveness:
    path: /ping
  readiness:
    path: /ping
  replicas:
    min: 2
    max: 4
  ingresses: 
{{#each ingresses}}
    - {{this}}
{{/each}}
  resources:
    limits:
      cpu: {{resources.limits.cpu}}
      memory: {{resources.limits.memory}}
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
  env:
{{#each envs}}
    - name: "{{name}}"
      value: "{{value}}"
{{/each}}
