# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  azure:
    application:
      enabled: true
  image: {{image}}
  port: {{PORT}}
  liveness:
    path: person/pdl-fullmakt-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: person/pdl-fullmakt-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: person/pdl-fullmakt-ui/internal/metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  {{ingressess}}
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  {{accesspolicies}}
  tokenx:
    enabled: true
  env:
    - name: API_GATEWAY_URL
      value: {{API_GATEWAY_URL}}
    - name: KTOR_ENV
      value: {{KTOR_ENV}}
TOKEN_X_WELL_KNOWN_URL: {{TOKEN_X_WELL_KNOWN_URL}}