# app=testapp ns=default; kubectl apply -f - <<< $(cat app.yaml | sed "s/{{ app }}/${app}/g" | sed "s/{{ ns }}/${ns}/g")

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ app }}
  name: {{ app }}
  namespace: {{ ns }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ app }}
  template:
    metadata:
      labels:
        app: {{ app }}
    spec:
      containers:
      - image: nais/testapp:latest
        imagePullPolicy: Always
        name: {{ app }}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: SOMEVAR
            value: SOMEVAL 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ app }}
  name: {{ app }}
  namespace: {{ ns }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ app }}
  type: ClusterIP
