---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: testapp
  namespace: default
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - namespaceSelector:
        matchLabels:
          name: nais
  podSelector:
    matchLabels:
      app: testapp
  policyTypes:
  - Ingress
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: testapp
  namespace: default
spec:
  rules:
  - methods:
    - '*'
    services:
    - testapp.default.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: testapp
  namespace: default
spec:
  roleRef:
    kind: ServiceRole
    name: testapp
  subjects:
  - user: cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
---
