apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp
  namespace: foreldrepenger
  labels:
    team: foreldrepenger
spec:
  image: docker.pkg.github.com/nais/testapp/testapp:2019-08-16-1f6cba0
  port: 8080
  liveness:
    path: /ping
  readiness:
    path: /ping
  replicas:
    min: 1
    max: 1
  ingresses: 
    - "https://testapp.dev-gcp.nais.io"
  env:
    - name: MY_CUSTOM_VAR
      value: some_value
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  skipCaBundle: true
