apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: a
  namespace: default
  labels:
    team: aura
spec:
  image: nais/testapp:latest
  port: 8080
  liveness:
    path: /ping
  readiness:
    path: /ping
  replicas:
    min: 1
    max: 2
  ingresses: 
    - "https://a.staging-gcp.nais.io"
  env:
    - name: MY_CUSTOM_VAR
      value: some_value
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    ingress:
      rules:
        - application: b
