name: Build and Deploy pdl-fullmakt-api


env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pdl-fullmakt-api:${{ github.sha }}

jobs:
  build-app:
    name: build-app
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set node environment
        uses: actions/setup-node@v1
        with:
          node-version: 11
      - run: npm ci
      - run: npm test

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
